CREATE TABLE IF NOT EXISTS NODES (ID BIGINT PRIMARY KEY NOT NULL, VERSION BIGINT, _TIMESTAMP TIMESTAMPTZ, UID BIGINT, USER_NAME TEXT, CHANGESET BIGINT, LAT DOUBLE PRECISION, LON DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS WAYS (ID BIGINT PRIMARY KEY NOT NULL, VERSION BIGINT, _TIMESTAMP TIMESTAMPTZ, UID BIGINT, USER_NAME TEXT, CHANGESET BIGINT);
CREATE TABLE IF NOT EXISTS RELATIONS (ID BIGINT PRIMARY KEY NOT NULL, VERSION BIGINT, _TIMESTAMP TIMESTAMPTZ, UID BIGINT, USER_NAME TEXT, CHANGESET BIGINT);
CREATE TABLE IF NOT EXISTS TAGS (TAGS_ID SERIAL PRIMARY KEY, K TEXT, V TEXT, ID BIGINT, FOREIGN KEY (ID) REFERENCES NODES (ID) ON DELETE CASCADE);
CREATE EXTENSION IF NOT EXISTS CUBE;
CREATE EXTENSION IF NOT EXISTS EARTHDISTANCE;